# -*- mode: makefile -*-

all: compile

init:
	sudo apt -y install TODO

compile: gvalue

run: compile
	./gvalue

gvalue: gvalue.c
	gcc -o gvalue gvalue.c `pkg-config --libs --cflags gobject-2.0`

clean:
	rm -f gvalue
