# -*- mode: makefile -*-

all: compile

init:
	sudo apt -y install TODO

compile: gvalue gvalue-from-gir

run: compile
	./gvalue
	./gvalue-from-gir

gvalue: gvalue.c
	gcc -g -o gvalue gvalue.c `pkg-config --libs --cflags gobject-2.0`

gvalue-from-gir: gvalue-from-gir.c debug.c
	 gcc -g -o gvalue-from-gir debug.c gvalue-from-gir.c `pkg-config --libs --cflags gobject-introspection-1.0`

clean:
	rm -f gvalue gvalue-from-gir
