# -*- mode: makefile -*-

all: compile

init:
	pacman --noconfirm -S --needed base-devel mingw-w64-x86_64-toolchain
	pacman --noconfirm -S mingw-w64-x86_64-gobject-introspection

compile: gvalue.c

run: compile
	./gvalue

dlls: compile
	ldd gvalue.exe | grep mingw | sed -E  's#[^/]*(/.*\.dll).*#\1#' | sort -u

gvalue.c:
	gcc -o gvalue gvalue.c `pkg-config --libs --cflags gobject-2.0`

clean:
	rm -f gvalue.exe
