# -*- mode: makefile -*-

all: compile

init:
	sudo apt -y install libgtk-3-dev libcairo2-dev

compile: hello-gtk hello-gtk-cairo

run: compile
	./hello-gtk && ./hello-gtk-cairo

hello-gtk: hello-gtk.c
	gcc -g -Wall -o hello-gtk hello-gtk.c `pkg-config --libs --cflags gtk+-3.0`

hello-gtk-cairo: hello-gtk-cairo.c
	gcc -g -Wall -o hello-gtk-cairo hello-gtk-cairo.c `pkg-config --libs --cflags gtk+-3.0`

clean:
	rm -f hello-gtk hello-gtk-cairo
